//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamAssessmentDaal
{
    using System;
    using System.Collections.Generic;
    
    public partial class FullExamTemplateInfo
    {
        public string ExamTemplateName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ExamTemplateID { get; set; }
        public string ExamQuestionID { get; set; }
        public string ExamQuestionName { get; set; }
        public string Description { get; set; }
        public string Answer { get; set; }
        public bool IsCorrect { get; set; }
    }
}
