//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamAssessmentDaal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject_Categories
    {
        public int Subject_Categories_ID { get; set; }
        public int Categories_ID { get; set; }
        public int Subject_ID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
