//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamAssessmentDaal
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwQuestionCategories
    {
        public int PKID { get; set; }
        public string ExamQuestionName { get; set; }
        public int QuestionTypeID { get; set; }
        public string ExamQuestionID { get; set; }
        public string Subject_Name { get; set; }
        public string Categories_Name { get; set; }
        public string Subtopic_Name { get; set; }
        public string Answer { get; set; }
    }
}
