//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamAssessmentDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamTemplate
    {
        public int PKID { get; set; }
        public string ExamTemplateName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ExamTemplateID { get; set; }
        public int ExamTypeID { get; set; }
    
        public virtual ExamType ExamType { get; set; }
    }
}
