//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamAssessmentDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamQuestion()
        {
            this.ExamQuestion_Categories = new HashSet<ExamQuestion_Categories>();
        }
    
        public int PKID { get; set; }
        public string ExamQuestionName { get; set; }
        public int QuestionTypeID { get; set; }
        public string ExamQuestionID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamQuestion_Categories> ExamQuestion_Categories { get; set; }
        public virtual QuestionType QuestionType { get; set; }
    }
}
