//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamAssessmentDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subtopic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subtopic()
        {
            this.Categories_Subtopic = new HashSet<Categories_Subtopic>();
        }
    
        public int Subtopic_ID { get; set; }
        public string Subtopic_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Categories_Subtopic> Categories_Subtopic { get; set; }
    }
}
