//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamAssessmentDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWFullQuestionInfo
    {
        public int QuestionID { get; set; }
        public string Description { get; set; }
        public int AnswerID { get; set; }
        public bool IsCorrect { get; set; }
        public string Answer { get; set; }
        public int LangaugeTypeId { get; set; }
        public string LanguageName { get; set; }
        public int PKID { get; set; }
        public string ExamQuestionName { get; set; }
        public int QuestionTypeID { get; set; }
        public string QuestionTypeName { get; set; }
        public string ExamQuestionID { get; set; }
        public Nullable<int> Subject_ID { get; set; }
        public string Subject_Name { get; set; }
        public Nullable<int> Categories_ID { get; set; }
        public string Categories_Name { get; set; }
        public Nullable<int> Subtopic_ID { get; set; }
        public string Subtopic_Name { get; set; }
    }
}
