//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamAssessmentDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWSubjectInfo
    {
        public int Subject_ID { get; set; }
        public string Subject_Name { get; set; }
        public Nullable<int> Categories_ID { get; set; }
        public string Categories_Name { get; set; }
        public Nullable<int> Subtopic_ID { get; set; }
        public string Subtopic_Name { get; set; }
    }
}
